# Generated by Django 4.1.9 on 2023-05-15 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admission',
            table='admissions',
        ),
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patients',
        ),
    ]
