# Generated by Django 4.1.9 on 2023-05-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_admission_table_alter_event_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='subject_id',
            field=models.IntegerField(default=999),
            preserve_default=False,
        ),
    ]
